### ISSUE TITLE
Pies deformed

### ISSUE THREAD

**Issue by GeohunterX** [cran/scatterpie#1]
As long as x and y coordinates are in the same dimension the package works fine. But in my case, I wanted to plot grain size composition of sediment samples as pies in a diagram with x-dimensions in the range of 0-9 and y-dimensions in the range of 1000-10000. Setting a radius of r = 1 let to pies that only appeared as flat lines since the radius apparently is dependent on the dimension of the axes.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by GeohunterX** [comment]
oh sorry - thank you for the hint!
